/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SUBSTRING_H_RPCGEN
#define _SUBSTRING_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct substring_data {
	char *str1;
	char *str2;
};
typedef struct substring_data substring_data;

#define SUBSTRING_PROG 0x20000001
#define SUBSTRING_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CHECK_SUBSTRING 1
extern  int * check_substring_1(substring_data *, CLIENT *);
extern  int * check_substring_1_svc(substring_data *, struct svc_req *);
extern int substring_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CHECK_SUBSTRING 1
extern  int * check_substring_1();
extern  int * check_substring_1_svc();
extern int substring_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_substring_data (XDR *, substring_data*);

#else /* K&R C */
extern bool_t xdr_substring_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SUBSTRING_H_RPCGEN */
