/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "substring.h"

int *
check_substring_1_svc(substring_data *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("The server has been started");
		
	if (strstr(argp->str1, argp->str2) != NULL) {
        result = 1; 
    } else {
        result = 0;
    }


	return &result;
}
