/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "substring.h"

bool_t
xdr_substring_data (XDR *xdrs, substring_data *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->str1, 100))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->str2, 100))
		 return FALSE;
	return TRUE;
}
